- include: ubuntu-setup.yml
  when: ansible_distribution == "Ubuntu"

- name: full system upgrade
  package:
    update_cache: yes
    upgrade: yes

- name: Install package
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ repos }}"

- name: Install Ubuntu packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ Ubuntu_repos }}"
  when: ansible_distribution == "Ubuntu"
