  - name: full system upgrade
    pacman:
      update_cache: yes
      upgrade: yes

  - name: Install package
    pacman:
      name: "{{ item }}"
      state: present
    with_items:
     - "{{ repos }}"

# - name: Install package
#   shell: echo "{{ item }}" >> /home/yann/tmp/ansible_repos.txt
#   with_items:
#    - "{{ repos }}"
